version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            pytest --maxfail=1 --disable-warnings -q

  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-app:latest .
      - run:
          name: Deploy to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push my-app:latest

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test

